export {
  TypeRegistry,
  type TypeDescriptor,
  type ParseContext,
  type SerializeContext,
  type TypeCapabilities,
  PRIMITIVE_CAPABILITIES,
  OBJECT_CAPABILITIES,
  ARRAY_CAPABILITIES,
  REF_CAPABILITIES,
  stringDescriptor,
  numberDescriptor,
  booleanDescriptor,
  objectDescriptor,
  arrayDescriptor,
  refDescriptor,
  createDefaultRegistry,
  defaultRegistry,
} from './descriptors/index';
